version: "3.1"
services:
  auth-service:
    build:
      context: .
      dockerfile: ./servers/auth/Dockerfile.dev
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: auth-service
    container_name: auth-service
    restart: unless-stopped
    volumes:
      - ./servers/auth:/app
    ports:
      - 8080:8080

  ws-service:
    build:
      context: .
      dockerfile: ./servers/ws/Dockerfile.dev
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: ws-service
    container_name: ws-service
    restart: unless-stopped
    volumes:
      - ./servers/ws:/app
    ports:
      - 8081:8080

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - SERVER_DOMAIN=localhost
    ports:
      - 80:80

  # database:
  #   image: postgres:14.0-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: auth
  #   ports:
  #     - 5432:5432
