version: "3.1"
services:
  auth-service:
    build:
      context: ./servers/auth
      dockerfile: Dockerfile
    hostname: auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - database

  ws-service:
    build:
      context: ./servers/ws
      dockerfile: Dockerfile
    hostname: ws-service
    container_name: ws-service
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - database

  database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - 5432:5432
