version: "3.1"
services:
  auth-service:
    build:
      context: .
      dockerfile: ./servers/auth/Dockerfile.dev
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: auth-service
    container_name: auth-service
    restart: unless-stopped
    volumes:
      - ./servers/auth:/app
    ports:
      - 8080:8080

  ws-service:
    build:
      context: .
      dockerfile: ./servers/ws/Dockerfile.dev
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: ws-service
    container_name: ws-service
    restart: unless-stopped
    volumes:
      - ./servers/ws:/app
    ports:
      - 8081:8080

  database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: beta-db
    ports:
      - 5432:5432

  cache:
    image: redis:6.2-alpine
    container_name: cache
    hostname: cache
    restart: unless-stopped
    command: redis-server --requirepass admin --appendonly yes
    ports:
      - 6379:6379
