version: "3.1"
services:
  auth-service:
    build:
      context: .
      dockerfile: ./servers/auth/Dockerfile.dev
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: auth-service
    container_name: auth-service
    restart: unless-stopped
    volumes:
      - ./servers/auth:/app
    ports:
      - 8080:8080

  ws-service:
    build:
      context: .
      dockerfile: ./servers/ws/Dockerfile.dev
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: ws-service
    container_name: ws-service
    restart: unless-stopped
    volumes:
      - ./servers/ws:/app
    ports:
      - 8081:8080

  client:
    image: node:18.10.0-alpine3.14
    platform: linux/amd64 # this is needed for M1 M2 Macs
    hostname: client
    container_name: client
    restart: unless-stopped
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: beta-db
    ports:
      - 5432:5432
