DatabaseURI: postgres://admin:admin@database:5432/beta-db?sslmode=disable
Environment: development
Domains:
  Client: https://beta.truongng.me
  Server: https://beta-api-v1.truongng.me
AllowedOrigins: ["*"]
JWT:
  Secretkey: "secret"
  RefreshTokenExpirationTime: 43200 # in minutes (30 days)
  AccessTokenExpirationTime: 60 # in minutes
Redis:
  Address: "cache:6379"
  Password: "admin"
  DB: 0
  PoolSize: 10
  MinIdleConns: 10
  IdleTimeout: 300
  MaxConnAge: 600
  ReadTimeout: 300
  WriteTimeout: 300
Email:
  Username: "The Poker"
  Password: "xvwapojesnlfzpog"
  From: "truongng201@gmail.com"
  FromName: "The Poker"
