// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: create.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token,
    ip_address,
    user_agent,
    device_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, user_id, token
`

type CreateRefreshTokenParams struct {
	UserID     int64       `json:"user_id"`
	Token      string      `json:"token"`
	IpAddress  string      `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	DeviceType pgtype.Text `json:"device_type"`
}

type CreateRefreshTokenRow struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceType,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.Token)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    username,
    email,
    hashed_password,
    image_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING user_id, email
`

type CreateUserParams struct {
	UserID         string      `json:"user_id"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
	ImageUrl       pgtype.Text `json:"image_url"`
}

type CreateUserRow struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.ImageUrl,
	)
	var i CreateUserRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}
