// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: delete.sql

package database

import (
	"context"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}
