// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: get.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    user_id,
    email,
    username,
    image_url,
    is_verified,
    hashed_password
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             int64       `json:"id"`
	UserID         string      `json:"user_id"`
	Email          string      `json:"email"`
	Username       string      `json:"username"`
	ImageUrl       pgtype.Text `json:"image_url"`
	IsVerified     bool        `json:"is_verified"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.ImageUrl,
		&i.IsVerified,
		&i.HashedPassword,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT
    users.id,
    refresh_tokens.id,
    users.user_id,
    users.email
FROM users
LEFT JOIN refresh_tokens
    ON users.id = refresh_tokens.user_id
WHERE refresh_tokens.token = $1 
    AND users.email = $2
`

type GetUserByRefreshTokenParams struct {
	Token string `json:"token"`
	Email string `json:"email"`
}

type GetUserByRefreshTokenRow struct {
	ID     int64       `json:"id"`
	ID_2   pgtype.Int8 `json:"id_2"`
	UserID string      `json:"user_id"`
	Email  string      `json:"email"`
}

func (q *Queries) GetUserByRefreshToken(ctx context.Context, arg GetUserByRefreshTokenParams) (GetUserByRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByRefreshToken, arg.Token, arg.Email)
	var i GetUserByRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.ID_2,
		&i.UserID,
		&i.Email,
	)
	return i, err
}

const healthCheck = `-- name: HealthCheck :one
SELECT 1 AS "one"
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var one int32
	err := row.Scan(&one)
	return one, err
}
