// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: health_check.sql

package database

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1 AS "one"
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var one int32
	err := row.Scan(&one)
	return one, err
}
