// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID         int64            `json:"id"`
	Token      string           `json:"token"`
	IpAddress  string           `json:"ip_address"`
	UserAgent  pgtype.Text      `json:"user_agent"`
	DeviceType pgtype.Text      `json:"device_type"`
	UserID     int64            `json:"user_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID             int64            `json:"id"`
	UserID         string           `json:"user_id"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
	ImageUrl       pgtype.Text      `json:"image_url"`
	IsVerified     bool             `json:"is_verified"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
