// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             uuid.UUID        `json:"id"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
	ImageUrl       pgtype.Text      `json:"image_url"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
