// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	VerifyEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
