// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteRefreshToken(ctx context.Context, token string) error
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByRefreshToken(ctx context.Context, arg GetUserByRefreshTokenParams) (GetUserByRefreshTokenRow, error)
	HealthCheck(ctx context.Context) (int32, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	VerifyEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
