// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"context"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (CheckEmailExistsRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	VerifyEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
