// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: reset_password.sql

package database

import (
	"context"
)

const resetPassword = `-- name: ResetPassword :exec
UPDATE users SET
    hashed_password = $2
WHERE email = $1
`

type ResetPasswordParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) error {
	_, err := q.db.Exec(ctx, resetPassword, arg.Email, arg.HashedPassword)
	return err
}
