// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: signin.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token,
    ip_address,
    user_agent,
    device_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, user_id
`

type CreateRefreshTokenParams struct {
	UserID     int64       `json:"user_id"`
	Token      string      `json:"token"`
	IpAddress  string      `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	DeviceType pgtype.Text `json:"device_type"`
}

type CreateRefreshTokenRow struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceType,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    user_id,
    email,
    username,
    image_url,
    is_verified,
    hashed_password
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             int64       `json:"id"`
	UserID         string      `json:"user_id"`
	Email          string      `json:"email"`
	Username       string      `json:"username"`
	ImageUrl       pgtype.Text `json:"image_url"`
	IsVerified     bool        `json:"is_verified"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.ImageUrl,
		&i.IsVerified,
		&i.HashedPassword,
	)
	return i, err
}
