// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: verify_email.sql

package database

import (
	"context"
)

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE users SET
    is_verified = TRUE
WHERE email = $1 AND is_verified = FALSE
`

func (q *Queries) VerifyEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, verifyEmail, email)
	return err
}
