name: Project Beta CI/CD ws service pipeline

on:
  push:
    branches:
      - main

jobs:
  check_folder_changed:
    name: Check if ws service folder changed
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.changes.outputs.service }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            servers:
              - 'servers/ws-service/**'

      # run only if "service" folder was changed
      - name: "ws service is changed"
        if: steps.changes.outputs.service == 'true'
        run: echo "Folder ws-service has changed"

      # run only if "service" folder was not changed
      - name: "ws service is not chnaged"
        if: steps.changes.outputs.service == 'false'
        run: echo "Folder ws-service has not changed"

  build_and_push:
    name: Build and Push ws Service Docker Image
    runs-on: ubuntu-latest
    needs: [check_folder_changed]
    if: needs.check_folder_changed.outputs.is_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build --build-args SERVICE_NAME=ws-service --build-arg SERVICE_VERSION=${{ secrets.GITHUB_SHA }} -t ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_REPOSITORY}}-ws-service:latest -f ./servers/ws/Dockerfile.prod .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_REPOSITORY}}-ws-service:latest

  pull_and_run_on_droplet:
    needs: [build_and_push]
    name: Pull and Run Docker Image on Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          cd ~/.ssh/ 
          touch id_rsa && touch known_hosts && chmod 600 id_rsa
          echo "${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Add Droplet to known hosts
        run: ssh-keyscan ${{ secrets.SERVER_IP_ADDRESS}} >> ~/.ssh/known_hosts

      - name: Pull and run Docker images on Droplet
        run: |
          ssh ${{ secrets.SERVER_USER}}@${{ secrets.SERVER_IP_ADDRESS}} 'docker pull ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_REPOSITORY}}-ws-service:latest'
          ssh ${{ secrets.SERVER_USER}}@${{ secrets.SERVER_IP_ADDRESS}} 'docker-compose up --build -d --force-recreate --remove-orphans ws-service'
